# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradefragment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GradeFragment', to='enrollment.UserProfile'),
        ),
        migrations.AlterField(
            model_name='lettergrade',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letter_grade', to='enrollment.UserProfile'),
        ),
    ]
