# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradefragment',
            name='boundary_range',
        ),
        migrations.AddField(
            model_name='gradefragment',
            name='boundary_range_lower',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='When the type is subjective and it is not free, give a negative range', max_digits=5, null=True, verbose_name='Boundary Range Lower'),
        ),
        migrations.AddField(
            model_name='gradefragment',
            name='boundary_range_upper',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='When the type is subjective and it is not free, give a positive range', max_digits=5, null=True, verbose_name='Boundary Range Upper'),
        ),
    ]
