# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-11 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_auto_20171011_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradefragment',
            name='student_total_grading',
            field=models.BooleanField(default=False, help_text='If this is checked, It will be calculated in the total mark', verbose_name='Calculate In Student Grading?'),
        ),
    ]
