# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 08:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_auto_20171023_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradefragment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GradeFragment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lettergrade',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letter_grade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
