# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_auto_20170607_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='updated_on',
            field=models.DateField(auto_now=True, null=True, verbose_name='Updated On'),
        ),
    ]
