# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0004_auto_20171107_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradefragment',
            name='entry_end_date',
            field=models.DateTimeField(help_text='Set the entry date and time to allow instructor to enter grades', null=True, verbose_name='Allowed entry end date'),
        ),
    ]
