# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0005_auto_20171108_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradefragment',
            name='allow_entry',
        ),
    ]
