# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0006_remove_gradefragment_allow_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgrade',
            name='updated_on',
            field=models.DateField(null=True, verbose_name='Updated On'),
        ),
    ]
