# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
        ('grade', '0007_auto_20171112_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='marker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.Assignment'),
        ),
        migrations.AlterField(
            model_name='gradefragment',
            name='boundary_type',
            field=models.CharField(choices=[('OBJECTIVE', 'Objective'), ('SUBJECTIVE_BOUNDED', 'Subjective bound'), ('SUBJECTIVE_BOUNDED_FIXED', 'Subjective bound Fixed'), ('SUBJECTIVE_FREE', 'Subjective Free')], default='SUBJECTIVE_FREE', max_length=24, null=True, verbose_name='Boundary Type'),
        ),
    ]
