# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-02 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0007_auto_20171112_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradefragment',
            name='boundary_type',
            field=models.CharField(choices=[('OBJECTIVE', 'Objective'), ('SUBJECTIVE_BOUNDED', 'Subjective bound'), ('SUBJECTIVE_BOUNDED_FIXED', 'Subjective bound Fixed'), ('SUBJECTIVE_FREE', 'Subjective Free')], default='SUBJECTIVE_FREE', max_length=24, null=True, verbose_name='Boundary Type'),
        ),
    ]
