# Generated by Django 2.0.1 on 2018-09-19 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0008_auto_20180702_1516'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grade', '0008_auto_20180702_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalStudentGrade',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('grade_quantity', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Student Grade Quantity')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instructor Remarks')),
                ('updated_on', models.DateField(null=True, verbose_name='Updated On')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('enrollment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='enrollment.Enrollment')),
                ('grade_fragment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='grade.GradeFragment')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical student grade',
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
