# Generated by Django 2.0.1 on 2018-11-07 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0008_auto_20180702_1516'),
        ('grade', '0009_historicalstudentgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradefragment',
            name='allow_markers_from_other_courses',
            field=models.NullBooleanField(default=False, help_text='If checked, it means you can assign markers in the subjective marking module from other courses within the same department', verbose_name='Allow Markers From Other Courses'),
        ),
        migrations.AddField(
            model_name='gradefragment',
            name='allow_markers_to_mark_own_students',
            field=models.NullBooleanField(default=False, help_text='If checked, it means the marker can mark students that he actually teaches', verbose_name='Allow Markers To Mark Own Students'),
        ),
        migrations.AddField(
            model_name='gradefragment',
            name='default_tie_breaking_marker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_marker', to='enrollment.Instructor', verbose_name='Default Tie-Breaking Marker'),
        ),
        migrations.AddField(
            model_name='gradefragment',
            name='exam_date',
            field=models.DateField(blank=True, null=True, verbose_name='Exam Date'),
        ),
        migrations.AddField(
            model_name='gradefragment',
            name='markings_difference_tolerance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The maximum difference allowed between different markings of a student paper before the intervention of a tie-breaker', max_digits=5, null=True, verbose_name='Markings Difference Tolerance'),
        ),
        migrations.AddField(
            model_name='gradefragment',
            name='number_of_markers',
            field=models.PositiveSmallIntegerField(blank=True, default=2, help_text='Indicates the number of markers that will subjectively mark students papers. If the number is 2,that means two markers will enter marks for each student paper and a third marker will break the tie if needed', null=True, verbose_name='Number Of Markers'),
        ),
    ]
