# Generated by Django 2.0.1 on 2018-12-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0010_auto_20181122_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradefragment',
            name='boundary_fixed_average',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Boundary Fixed Average'),
        ),
        migrations.AlterField(
            model_name='gradefragment',
            name='boundary_range_lower',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='When the type is subjective and it is not free, give a negative range', max_digits=10, null=True, verbose_name='Boundary Range Lower'),
        ),
        migrations.AlterField(
            model_name='gradefragment',
            name='boundary_range_upper',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='When the type is subjective and it is not free, give a positive range', max_digits=10, null=True, verbose_name='Boundary Range Upper'),
        ),
        migrations.AlterField(
            model_name='gradefragment',
            name='weight',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='historicalstudentgrade',
            name='grade_quantity',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Student Grade Quantity'),
        ),
        migrations.AlterField(
            model_name='lettergrade',
            name='cut_off_point',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10, null=True, verbose_name='Cut off Point'),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='grade_quantity',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Student Grade Quantity'),
        ),
    ]
