# Generated by Django 2.0.1 on 2018-12-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0013_courses_averages_db_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesAveragesView',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('semester_code', models.CharField(max_length=20)),
                ('course_code', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=4, max_digits=10)),
                ('grades_average', models.DecimalField(decimal_places=4, max_digits=10)),
                ('grades_average_percentage', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'grade_coursesaveragesview',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SectionsAveragesView',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('semester_code', models.CharField(max_length=20)),
                ('course_code', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=4, max_digits=10)),
                ('grades_average', models.DecimalField(decimal_places=4, max_digits=10)),
                ('grades_average_percentage', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'grade_sectionsaveragesview',
                'managed': False,
            },
        ),
    ]
