# Generated by Django 2.0.1 on 2018-12-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0015_sections_objective_averages_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionsObjectiveAveragesView',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('semester_code', models.CharField(max_length=20)),
                ('course_code', models.CharField(max_length=20)),
                ('weights_sum', models.DecimalField(decimal_places=4, max_digits=10)),
                ('grades_objective_average', models.DecimalField(decimal_places=4, max_digits=10)),
                ('grades_objective_average_percentage', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'db_table': 'grade_sectionsobjectiveaveragesview',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='gradefragment',
            name='show_teacher_report',
            field=models.BooleanField(default=True, help_text='This flag will control whether teachers are be able to see grades of this fragment in darajati or in BI', verbose_name='Show in Teacher Report'),
        ),
    ]
