# Generated by Django 2.0.1 on 2018-12-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0016_auto_20181216_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradefragment',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated On'),
        ),
        migrations.AlterField(
            model_name='historicalstudentgrade',
            name='updated_on',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Updated On'),
        ),
        migrations.AlterField(
            model_name='lettergrade',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated On'),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated On'),
        ),
    ]
