# Generated by Django 2.0.1 on 2018-12-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0017_auto_20181227_1121'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS grade_sectionsobjectiveaveragesview;
            
            DROP VIEW IF EXISTS grade_sectionsobjaveragesview;
            
            CREATE OR REPLACE VIEW grade_sectionsobjaveragesview AS 
            SELECT
                ROW_NUMBER() OVER () AS ID,
                Q.SEMESTER_ID,
                Q.SEMESTER_CODE,
                Q.COURSE_ID,
                Q.COURSE_CODE,
                Q.SECTION_ID,
                Q.SECTION_CODE,
                SUM(Q.WEIGHT) WEIGHTS_SUM,
                ((SUM(Q.GRADES_AVERAGE_PERCENTAGE * Q.WEIGHT) / SUM(Q.WEIGHT)) / 100) * SUM(Q.WEIGHT) GRADES_OBJECTIVE_AVERAGE,
                SUM(Q.GRADES_AVERAGE_PERCENTAGE * Q.WEIGHT) / SUM(Q.WEIGHT) GRADES_OBJECTIVE_AVERAGE_PERCENTAGE
            FROM (
            SELECT 
                SEMESTER_ID,
                SEMESTER_CODE,
                COURSE_ID,
                COURSE_CODE,
                SECTION_ID,
                SECTION_CODE,
                GRADE_FRAGMENT_ID,
                CATEGORY,
                DESCRIPTION,
                WEIGHT,
                GRADES_AVERAGE,
                GRADES_AVERAGE_PERCENTAGE FROM GRADE_SECTIONSAVERAGESVIEW
            WHERE
                BOUNDARY_TYPE = 'OBJECTIVE'
            ) Q
            GROUP BY
                Q.SEMESTER_ID,
                Q.SEMESTER_CODE,
                Q.COURSE_ID,
                Q.COURSE_CODE,
                Q.SECTION_ID,
                Q.SECTION_CODE;
            """
        ),
    ]
