# Generated by Django 2.0.1 on 2018-12-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0018_shorten_view_name_and_remove_column_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sectionsobjectiveaveragesview',
            table='grade_sectionsobjaveragesview',
        ),
    ]
