# Generated by Django 2.0.1 on 2019-01-01 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0009_auto_20181227_1320'),
        ('grade', '0021_grade_studentfinaldataview'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFinalDataView',
            fields=[
                ('semester_code', models.CharField(max_length=20)),
                ('department_code', models.CharField(max_length=20)),
                ('course_code', models.CharField(max_length=20)),
                ('coordinated', models.BooleanField()),
                ('section_code', models.CharField(max_length=20)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='final_data', serialize=False, to='enrollment.Enrollment')),
                ('letter_grade', models.CharField(max_length=20)),
                ('active', models.BooleanField()),
                ('university_id', models.CharField(max_length=20)),
                ('english_name', models.CharField(max_length=255)),
                ('arabic_name', models.CharField(max_length=255)),
                ('total_weights', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total', models.DecimalField(decimal_places=4, max_digits=10)),
                ('attendance_deduction', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total_after_deduction', models.DecimalField(decimal_places=4, max_digits=10)),
                ('total_rounded', models.DecimalField(decimal_places=4, max_digits=10)),
                ('calculated_letter_grade', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'grade_studentfinaldataview',
                'managed': False,
            },
        ),
    ]
