# Generated by Django 2.0.1 on 2019-01-15 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0023_auto_20190106_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lettergrade',
            options={'ordering': ('course_offering', 'section', '-cut_off_point', 'letter_grade')},
        ),
        migrations.AlterField(
            model_name='gradefragment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_grade_fragments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lettergrade',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_letter_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
