# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledperiod',
            name='absence_deduction',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='absence deduction'),
        ),
        migrations.AlterField(
            model_name='scheduledperiod',
            name='late_deduction',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='late deduction'),
        ),
    ]
