# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledperiod',
            name='absence_deduction',
        ),
        migrations.RemoveField(
            model_name='scheduledperiod',
            name='late_deduction',
        ),
    ]
