# Generated by Django 2.0.1 on 2018-12-19 06:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('attendance', '0004_auto_20181122_1514'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION attendance_boundary(
                num1 numeric,
                num2 numeric)
              RETURNS numeric AS
            $BODY$
            DECLARE 
            BEGIN
            
              IF num1 > num2 THEN
                  return num1 - num2;
              ELSE
                  return 0;
              END IF;
            
            END; 
            $BODY$
            LANGUAGE plpgsql VOLATILE
            """
        )
    ]
