# Generated by Django 2.0.1 on 2018-12-19 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_enrollment_attendance_deduction'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS enrollment_attendancedeductionview;
            
            CREATE OR REPLACE VIEW enrollment_attendancedeductionview AS 
            SELECT ROW_NUMBER() OVER () AS ID, E.ID ENROLLMENT_ID, ENROLLMENT_ATTENDANCE_DEDUCTION(E.ID)
            FROM ENROLLMENT_ENROLLMENT E;
            """
        )
    ]
