# Generated by Django 2.0.1 on 2018-12-27 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_enrollment_attendancedeductionview'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS enrollment_attendancedeductionview;
            DROP FUNCTION IF EXISTS enrollment_attendance_deduction(enrollment_id integer);
            """
        ),
    ]
