# Generated by Django 2.0.1 on 2018-12-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_attendance_deduction_function'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS enrollment_attendancededuction;
            
            CREATE OR REPLACE VIEW enrollment_attendancededuction AS 
            SELECT ROW_NUMBER() OVER () AS ID, E.ID ENROLLMENT_ID, ATTENDANCE_DEDUCTION(E.ID)
            FROM ENROLLMENT_ENROLLMENT E;
            """
        ),
    ]
