# Generated by Django 2.0.1 on 2019-01-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_attendance_boundary_function_immutable'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DROP VIEW IF EXISTS enrollment_attendancededuction;
            
            CREATE OR REPLACE VIEW enrollment_attendancededuction AS 
            SELECT E.ID ENROLLMENT_ID, ATTENDANCE_DEDUCTION(E.ID)
            FROM ENROLLMENT_ENROLLMENT E;
            """
        ),
    ]
