# Generated by Django 2.0.1 on 2019-06-26 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_auto_20190115_1502'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendanceinstance',
            unique_together={('period', 'date')},
        ),
    ]
