# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0002_auto_20171010_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='allow_change',
            field=models.BooleanField(default=1, help_text='This if checked will allow the instructors to change the attendances after submitting', verbose_name='Allow changing after submitting attendance?'),
        ),
    ]
