# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0006_auto_20171108_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='formula',
            field=models.CharField(blank=True, help_text='Formula to calculate the deduction value from students attendance', max_length=200, null=True, verbose_name='Deduction formula'),
        ),
    ]
