# Generated by Django 2.2.3 on 2019-07-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0012_courseoffering_letter_grade_promotion_borderline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseoffering',
            old_name='letter_grade_promotion_borderline',
            new_name='grade_promotion_borderline',
        ),
    ]
