# Generated by Django 2.2.3 on 2019-11-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0013_auto_20190729_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='auto_grade_promotion_difference',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, help_text='This will be used to check students eligibility for letter grade promotion. A student will be considered for promotion if his total is within this difference', max_digits=10, null=True, verbose_name='Auto Letter Grade Promotion Difference'),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='grade_promotion_borderline',
            field=models.DecimalField(blank=True, decimal_places=4, default=0.0, help_text='This will be used to check students eligibility for letter grade promotion if the student is meeting promotion criterion in the grade fragment(s)', max_digits=10, null=True, verbose_name='Letter Grade Promotion Borderline Difference For Criteria'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='letter_grade',
            field=models.CharField(blank=True, default='UD', max_length=20, null=True, verbose_name='letter grade'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='register_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enrollment Date'),
        ),
        migrations.AlterField(
            model_name='historicalenrollment',
            name='letter_grade',
            field=models.CharField(blank=True, default='UD', max_length=20, null=True, verbose_name='letter grade'),
        ),
        migrations.AlterField(
            model_name='historicalenrollment',
            name='register_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Enrollment Date'),
        ),
    ]
