# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-21 09:13
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(null=True, verbose_name='Room Capacity')),
            ],
            options={
                'ordering': ['exam_shift', 'room'],
            },
        ),
        migrations.CreateModel(
            name='ExamShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Shift Start Date')),
                ('end_date', models.DateTimeField(null=True, verbose_name='Shift End Date')),
            ],
            options={
                'ordering': ['fragment', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='This is the order in which after marker 1 finish the markings for marker 2 will start..', null=True, verbose_name='Marking Order')),
                ('generosity_factor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Generosity factor for this instructor, can be in minus. Make sure it is in percent', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-100.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Generosity Factor')),
                ('is_a_monitor', models.BooleanField(default=False, verbose_name='Is a Monitor?')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
            ],
            options={
                'ordering': ['exam_room', 'order', 'instructor'],
            },
        ),
        migrations.CreateModel(
            name='StudentMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Student Grade Quantity')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated On')),
            ],
            options={
                'ordering': ['student_placement', 'marker'],
            },
        ),
        migrations.CreateModel(
            name='StudentPlacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True, verbose_name='Is Present?')),
                ('shuffled_on', models.DateTimeField(auto_now=True, verbose_name='Shuffled On')),
            ],
            options={
                'ordering': ['enrollment'],
            },
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='AssignmentInstance',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='coordinator',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='room',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='updated_by',
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['location']},
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='Room Capacity'),
        ),
    ]
