# Generated by Django 2.0.1 on 2018-12-03 12:13

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examsettings',
            name='markings_difference_tolerance',
            field=models.DecimalField(decimal_places=4, help_text='The maximum difference allowed between different markings of a student paper before the intervention of a tie-breaker', max_digits=10, null=True, verbose_name='Markings Difference Tolerance'),
        ),
        migrations.AlterField(
            model_name='historicalmarker',
            name='generosity_factor',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Generosity factor for this instructor, can be in minus. Make sure it is in percent', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-100.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Generosity Factor'),
        ),
        migrations.AlterField(
            model_name='historicalstudentmark',
            name='mark',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Student Grade Quantity'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='generosity_factor',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.00'), help_text='Generosity factor for this instructor, can be in minus. Make sure it is in percent', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-100.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Generosity Factor'),
        ),
        migrations.AlterField(
            model_name='studentmark',
            name='mark',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Student Grade Quantity'),
        ),
    ]
