# Generated by Django 2.2.3 on 2019-07-29 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20181203_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmarker',
            name='exam_room',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='exam.ExamRoom', verbose_name='Instructor'),
        ),
        migrations.AlterField(
            model_name='historicalmarker',
            name='instructor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='enrollment.Instructor', verbose_name='Instructor'),
        ),
        migrations.AlterField(
            model_name='historicalmarker',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AlterField(
            model_name='historicalstudentmark',
            name='student_placement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='exam.StudentPlacement', verbose_name='Student Placement'),
        ),
    ]
