# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-21 09:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20181021_1213'),
        ('grade', '0009_auto_20181021_1213'),
        ('enrollment', '0008_auto_20171214_1136'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='enrollment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='enrollment.Enrollment'),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='exam_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='exam.ExamRoom', verbose_name='Exam Room'),
        ),
        migrations.AddField(
            model_name='studentplacement',
            name='shuffled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Shuffled By'),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='marker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='markings', to='exam.Marker'),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='student_placement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='exam.StudentPlacement', verbose_name='Student Placement'),
        ),
        migrations.AddField(
            model_name='studentmark',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marker',
            name='exam_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='exam.ExamRoom', verbose_name='Instructor'),
        ),
        migrations.AddField(
            model_name='marker',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marking', to='enrollment.Instructor', verbose_name='Instructor'),
        ),
        migrations.AddField(
            model_name='marker',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Updated By'),
        ),
        migrations.AddField(
            model_name='examshift',
            name='fragment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams_shifts', to='grade.GradeFragment', verbose_name='Fragment'),
        ),
        migrations.AddField(
            model_name='examroom',
            name='exam_shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exam.ExamShift', verbose_name='Exam Shift'),
        ),
        migrations.AddField(
            model_name='examroom',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exam.Room', verbose_name='Exam Room'),
        ),
    ]
